### ISSUE TITLE
Project logos

### ISSUE THREAD

**Issue by RedVelvetZip** [bitcoinlayers/bitcoinlayers#12]
Logos for layers in pubic/logos/[layer.slug].png
based on the slug from content/layers/[layer].json

also needed for Infrastructure and Bridges, same locations and formatting

**Comment by januszgrze** [comment]
I completed this.https://github.com/bitcoinlayers/bitcoinlayers/commit/2c44f7ec91ff7eab7a378164fdefac7a6122c965

**Comment by RedVelvetZip** [comment]
Fixed
