### ISSUE TITLE
UI - Add "Beta" to Status

### ISSUE THREAD

**Issue by januszgrze** [bitcoinlayers/bitcoinlayers#154]
We need to have an option for "beta" for status related to bitcoin protocols that can be built on mainnet, but probably shouldn't be. E.g. Mercury Layer is on mainnet, but I'm not sure we should classify it in the same light as LN.

I don't know how to word this. Beta is the wrong word, but opening this so we're aware that it needs to get done.

**Comment by bolander72** [comment]
Same as #91?

**Comment by januszgrze** [comment]
completed this.
