### ISSUE TITLE
Minor UX/UI improvements to home page

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoinlayers/bitcoinlayers#20]
### Navigation
- [ ] Add hover state to nav items
**Default:** storm-gray-700 #767B8F
**Hover:** link-water-900 #434D65
![CleanShot 2024-07-04 at 01 53 44@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/4f2857b8-85b1-463f-939e-e1da7ff0c7de)

- [ ] Make hover in Analysis popup lighter (zircon-50, #F5F8FD)

### Header
- [ ] add gradient to hero ("Layers"). Gradient: left: #FE4F18 right: #FF6C19 - (If it's not easy in CSS then leave it as it is)

### Search input
- [ ] add vertical trim to make the placeholder look more centered (this may be not easy in CSS, if there's no easy workaround they let's just leave it as it is)

- [ ] add 4% letter spacing

### Toggle buttons
- [ ] make Overview and Risk buttons same fixed size w-24 (96px)

- [ ] add hover state to unselected button, (fill: zircon-50)
![CleanShot 2024-07-04 at 02 03 55@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/c275c92b-fb00-48b4-9b48-fe6711e6965e)

### Table
- [ ] make tabletop less high (h-14 3.5rem 56px ) - I know the problem is "Unit of Account" which I shortened to "Unit". Maybe we can use Base Unit and make eg. Type cell a bit shorter?

- [ ] add short "dividers" in table top in "Risks", same as are in "Overview"

- [ ] fix table corners - there's something weird with them, especially at the bottom 
![CleanShot 2024-07-04 at 02 09 39@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/066c94ec-bd06-4cf9-9925-ca84cf5825e6)
![CleanShot 2024-07-04 at 02 09 58@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/047a8a68-9d7d-4e41-ae2d-0aaa8e24f9c3)

- [ ] make border stroke consistent and same color - all should have 1px with zircon-100 (#E1EAF8). For some reason the left side of the table seems to be thinner and different color

![CleanShot 2024-07-04 at 02 12 13@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/a8d3dac7-b546-4805-8c11-f1284b61e33f)

- [ ] make cell text color a bit lighter: link-water-900 / #434D65 / rgba(67, 77, 101, 1)

- [ ] add hover state to whole layer row (we can use the same color as tabletop, zircon-100 #F5F8FD)

- [ ] center bridge icon - I don't know why it appears not centerd, I see in inspect it should be centred. Sharing svg here again just in case. If it's not easily fixable with CSS I can edit the icon maybe that will help
![arrows](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/3fa4c948-bf57-40b3-9ae4-f846d0356373)
![CleanShot 2024-07-04 at 02 19 08@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/39a9ced6-3d4e-4e41-a888-08be4942de9b)

### Bottom
- [ ] make divider same length as table, 1px and lighter (link-water-200, D3DDE8)

- [ ] align logo and copy to the left - this is purerly subjective for me but I prefer it when it aligns to the left :P 
![CleanShot 2024-07-04 at 02 23 38@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/b722e22e-c515-4fb1-9724-e4b45fd31c5d)

- [ ] add hover state to social icon buttons (link-water-900 #434D65)

**Comment by januszgrze** [comment]
@bolander72 - close since new UI is going to be different?
