### ISSUE TITLE
Add sorting to "Risk" column

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoinlayers/bitcoinlayers#21]
Adding sorting there could quickly allow users to see lowest risk (with highest score) layers at the top

Related discussion: https://x.com/StackingSaunter/status/1808662211511951444

**Comment by januszgrze** [comment]
We don't really aggregate risk scores... should we do some simple math to give them a score?

e.g. low = 1, medium = 2, high = 3

so risk for rootstock is (3+2+2+2) / 4 = 2.25

wdyt @RedVelvetZip - I actually don't want to take a strong position on assigning an overall risk to a project

**Comment by stackingsaunter** [comment]
@januszgrze yes, keep it simple now withc just, more green, it lands at the top

then when we add real scoring it will be more granual

**Comment by RedVelvetZip** [comment]
closed as we are not sorting Risk with an overall score
