### ISSUE TITLE
Add filters to the table

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoinlayers/bitcoinlayers#22]
Filers will allow to eg. filter out "under review" or to show only layers of certain type, or only with BTC as unit of account.

Filters design and handoff are here:
https://www.figma.com/design/pRLfQ8OXsOZLsaRaiZ1auw/Bitcoin-Layers?node-id=533-143464&t=QnXN2DYhP6x9IMRG-4

Also @RedVelvetZip take note this is from Ant Design, which maybe you can copy the code somehow? (although it's not tailswind based I think. Feel free to use some ready component for tailwind and just theme it in our style)

![CleanShot 2024-07-04 at 02 44 21@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/7466db67-48ab-4377-bf32-4870255d8925)

Proposed options for filters:

### Risks:
- Reviewed
- Under Review

### Type:
- each type

### Status
- each status. If we show ONLY mainnet on home, [then we can delete this column ](https://github.com/bitcoinlayers/bitcoinlayers/issues/23)

### Unit of Account
- Bitcoin
- Other

**Comment by januszgrze** [comment]
I think we need to keep status and delete the upcoming layers page. people don't seem to be finding the page when visiting the site.

**Comment by januszgrze** [comment]
So testnet status would show by default, but you could filter to that.

**Comment by stackingsaunter** [comment]
@januszgrze I agree. I think by default we should show all and in alphabetical order.
Anything else user can hide themself

**Comment by RedVelvetZip** [comment]
filters are live shoutout @bolander72
