### ISSUE TITLE
Delete "Status" from Home Overview table?

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoinlayers/bitcoinlayers#23]
I see we show only Mainnet layers, and Upcoming have a seperate page.
If we show only mainnet and want to keep it this way, we can delete this column and make it more spacey and have more breath

cc @januszgrze

**Comment by januszgrze** [comment]
I think we want to add filtering. Not sure how that would affect this.

**Comment by stackingsaunter** [comment]
@januszgrze then you want to show upcoming and mainnet in one table?

In that case I'd keep Status, If you want keep them seperate, then Status maybe can be only on Upcoming (since it can be testnet/pre-testnet etc)

**Comment by RedVelvetZip** [comment]
Closing this issue
Status remains as a table item as the new filter options allow mainnet/testnet layers to be shown in the same view
