### ISSUE TITLE
Update to risk chart

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoinlayers/bitcoinlayers#25]
![CleanShot 2024-07-09 at 16 27 54@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/5f6f7f87-9136-44df-ba02-d2ed697f6d88)

**Fonts:** 
Category: text-sm medium
Risks: text-xs semibold

**Bg colors:**
- low risk: lima-100 / #DFFBCC
- medium risk: clementine-100 / #FFF1C6
- high risk: coral-red-100 / #FFDFDF
- critical risk coral-red-300 / #FF9D9E

**Updates**

Text colors:
- medium risk: clementine-600 / #DD6B02
- critical risk coral-red-800 / #A50F11

Icon colors:
- medium risk: clementine-500 / #F99107
- critical risk coral-red-700 / #C80D0F

**Comment by RedVelvetZip** [comment]
Colors updated; text within risk diamond will not be added
