### ISSUE TITLE
Change highlighted text color

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoinlayers/bitcoinlayers#27]
Highlighted text is not readable now

![CleanShot 2024-07-09 at 17 33 38@2x](https://github.com/bitcoinlayers/bitcoinlayers/assets/68239231/404bfa1a-f480-4ec9-9c11-d206a20e87e4)

We can change it to white, and highlight color to brand bloody orange maybe?

**Comment by RedVelvetZip** [comment]
@stackingsaunter can you please share the device and browser your screenshot is from? Not seeing this behavior on firefox or chromium-based browsers (brave/chrome)

**Comment by stackingsaunter** [comment]
Arc browsers / macbook pro

**Comment by RedVelvetZip** [comment]
@stackingsaunter can you confirm if this issue still persists?

**Comment by stackingsaunter** [comment]
All good now
