### ISSUE TITLE
Add "Critical Risk" variable and as-needed section

### ISSUE THREAD

**Issue by januszgrze** [bitcoinlayers/bitcoinlayers#31]
We need to add a section that outlines very critical risks that are out of scope for our assessment. This should be put in the file as a "yes/no" variable, and if yes, the critical risk section appears above the risk assessment.

We'd also need to add some icon to the home page that would sit next to the project in the event the variable is yes. 

This seems relatively simple to do.

**Comment by RedVelvetZip** [comment]
Done
