### ISSUE TITLE
Clean up UI for the methodology page

### ISSUE THREAD

**Issue by januszgrze** [bitcoinlayers/bitcoinlayers#72]
to-do for @januszgrze

**Comment by john-light** [comment]
Does this issue include things like the word "layers" not being fully visible?

![Screenshot from 2024-10-14 18-37-12](https://github.com/user-attachments/assets/4786c726-7a1c-4b42-b7e1-daa64de06872)

**Comment by januszgrze** [comment]
interesting. my browser on desktop and mobile is working?

I think I already finished what i set out to do here. but if this is an issue it's something to look into @RedVelvetZip @bolander72

**Comment by bolander72** [comment]
I am not have issues either. @john-light can you share any OS, browser, device info that can help us troubleshoot?

**Comment by john-light** [comment]
Browser: Firefox 131.0 (64-bit)
OS: Linux Mint 21

**Comment by bolander72** [comment]
@john-light let me know if this css jank persists for you. Going to close the ticket for now given no new reports of this.

**Comment by john-light** [comment]
@bolander72  it is still there for me, even in an incognito window.
