### ISSUE TITLE
ilike operator for project TVL charts can't find certain projects via API/DB

### ISSUE THREAD

**Issue by bolander72** [bitcoinlayers/bitcoinlayers#94]
Internet Computer
Lightning Network
Merlin
Rollux

**Comment by john-light** [comment]
Is this issue referring to this bug I found where certain projects aren't showing their TVL chart to match the TVL shown at the top of the page? If so you can add Stacks to the list (I haven't checked all of them)

![Screenshot from 2024-10-14 18-57-40](https://github.com/user-attachments/assets/8affd8c9-1365-4033-8d45-9024d5164cb8)

**Comment by bolander72** [comment]
@john-light I think you beat us to getting data populated in the chart. Can you try again?

I'm seeing the chart and top-of-page TVL displaying properly with the same number (501 BTC currently)

**Comment by bolander72** [comment]
closing now that we are searching via slugs rather than names
