### ISSUE TITLE
DB layer names and JSON file layer names using different casing

### ISSUE THREAD

**Issue by bolander72** [bitcoinlayers/bitcoinlayers#95]

**Comment by RedVelvetZip** [comment]
maybe we should match to "layer_slug" instead of "layer_name"?

layer slugs have no spaces and are fully lowercase

**Comment by bolander72** [comment]
Hey @RedVelvetZip, "layer_slug" gets returned in the GET call for /layers. The call we are making to retrieve TVL is /get_balances.

This response does not contain "layer_slug".

Ideally, I am not making two separate calls to get the data I need and then a supplemental property that I need to map into my TVL array.

I propose adding "layer_slug" to /balances and /get_balances GET calls in API/DB, given we can't rely on the "layer_name" property being consistent between JSON and DB.
